### ISSUE TITLE
java.lang.NoClassDefFoundError: android.media.session.MediaSessionManager

### ISSUE THREAD

**Issue by yogeshalai** [valdio/AudioPlayer#5]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  java.lang.NoClassDefFoundError: android.media.session.MediaSessionManager
                                                                                      at com.valdioveliu.valdio.audioplayer.MediaPlayerService.initMediaSession(MediaPlayerService.java:447)
                                                                                      at com.valdioveliu.valdio.audioplayer.MediaPlayerService.onStartCommand(MediaPlayerService.java:127)
                                                                                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2846)
                                                                                      at android.app.ActivityThread.access$2000(ActivityThread.java:168)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                      at android.os.Looper.loop(Looper.java:176)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by Smarpit-Singh** [comment]
It will work perfectly 

setStyle(new android.support.v4.media.app.NotificationCompat.MediaStyle()
                        // Attach our MediaSession token
                        .setMediaSession(mediaSession.getSessionToken())
                        // Show our playback controls in the compat view
                        .setShowActionsInCompactView(0, 1, 2))
